"""add entrada fiscal

Revision ID: de77a42fede1
Revises: 
Create Date: 2026-04-08 14:27:59.540764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de77a42fede1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrada_fiscal_por', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_entrada_fiscal', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.drop_column('data_entrada_fiscal')
        batch_op.drop_column('entrada_fiscal_por')

    # ### end Alembic commands ###
